(() => {
  const C=window.VillageCore,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  const host=$('#jobAutonomy');if(!C||!host||!C.buildingWorkDefs)return;
  const jobId=document.body.dataset.job||'',building=(C.content.buildings||[]).find(b=>b.jobId===jobId);if(!building)return;
  const resText=obj=>Object.entries(obj||{}).map(([id,q])=>`${C.content.resources.find(r=>r.id===id)?.icon||'📦'} ${q} ${C.content.resources.find(r=>r.id===id)?.name||id}`).join(' · ')||'—';
  function render(){C.processBuildingWork();const st=C.buildingWorkStatus(building.id),stats=C.autonomyStats(),defs=C.buildingWorkDefs(building.id),now=Date.now();
    host.innerHTML=`<div class="autonomy-summary"><div><span>Emplacements</span><b>${st.active.length+st.blocked.length}/${st.slots}</b></div><div><span>Travailleurs</span><b>${stats.workersBusy}/${stats.workersTotal}</b></div><div><span>File</span><b>${st.queued.length}</b></div><div><span>Entrepôt</span><b>${Math.round(C.storageFree())} libre</b></div></div>${st.orders.length?`<div class="autonomy-active-list">${st.orders.map(o=>{const d=C.workDef(o.defId);if(!d)return'';const left=o.status==='running'?C.autonomyFormatDuration(o.endsAt-now):o.status==='waiting_storage'?'Stockage bloqué':'En file';return `<div class="autonomy-active ${o.status}"><span>${d.icon||'⚙️'}</span><div><b>${esc(d.name)}</b><small>${left}${o.status==='waiting_storage'?' · libère de la place dans l’Entrepôt':''}</small></div>${o.status==='queued'?`<button class="mini-link" data-cancel-work="${o.id}">Retirer</button>`:''}</div>`;}).join('')}</div>`:'<div class="empty-state compact"><b>Aucun job autonome</b><span>Le travail manuel reste disponible indépendamment.</span></div>'}<div class="autonomy-order-grid">${defs.map(d=>{const gate=C.autonomyRequirementMessages(d),hard=gate.filter(x=>x.startsWith('Bâtiment')||x.includes(' niv. ')),input=gate.filter(x=>!hard.includes(x));return `<article class="autonomy-order"><div><span>${d.icon||'⚙️'}</span><b>${esc(d.name)}</b></div><small>${Math.round(d.duration)}s · ${d.workers||1} travailleur · sorties : ${esc(resText(d.outputs))}</small>${Object.keys(d.inputs||{}).length?`<small>Entrées : ${esc(resText(d.inputs))}</small>`:''}${hard.length?`<em>🔒 ${esc(hard.join(' · '))}</em>`:input.length?`<em>⏳ ${esc(input.join(' · '))}</em>`:''}<div><button class="btn" data-queue-work="${d.id}" ${hard.length||st.orders.length>=12?'disabled':''}>+1 job</button><button class="btn" data-queue-work3="${d.id}" ${hard.length||st.orders.length>=10?'disabled':''}>+3</button></div></article>`;}).join('')}</div><div class="notice subtle"><b>Travail autonome ≠ geste technique.</b> Ces ordres produisent des ressources communes avec un rendement volontairement inférieur. Raretés, lots de haute qualité, puzzles et décisions fines restent liés au travail actif du joueur.</div>`;
    host.querySelectorAll('[data-queue-work]').forEach(b=>b.onclick=()=>{C.queueBuildingWork(building.id,b.dataset.queueWork,1);render();});host.querySelectorAll('[data-queue-work3]').forEach(b=>b.onclick=()=>{C.queueBuildingWork(building.id,b.dataset.queueWork3,3);render();});host.querySelectorAll('[data-cancel-work]').forEach(b=>b.onclick=()=>{C.cancelBuildingWork(building.id,b.dataset.cancelWork);render();});
  }
  render();setInterval(render,500);window.addEventListener('village:autonomy',render);
})();
