(() => {
  const C=window.VillageCore;if(!C||C._autonomyReady)return;C._autonomyReady=true;
  const uid=()=>globalThis.crypto?.randomUUID?.()||`bw_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;
  const now=()=>Date.now();
  const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
  const state=C.state;
  if(!state.buildingWork||typeof state.buildingWork!=='object')state.buildingWork={};
  if(!state.villageStats||typeof state.villageStats!=='object')state.villageStats={};
  if(typeof state.villageStats.autonomousJobsCompleted!=='number')state.villageStats.autonomousJobsCompleted=0;
  if(typeof state.villageStats.autonomousJobsQueued!=='number')state.villageStats.autonomousJobsQueued=0;

  function workDef(id){return (C.content.buildingWorkOrders||[]).find(x=>x.id===id)||null;}
  function defsFor(buildingId){return (C.content.buildingWorkOrders||[]).filter(x=>x.buildingId===buildingId);}
  function workState(buildingId){if(!state.buildingWork[buildingId]||typeof state.buildingWork[buildingId]!=='object')state.buildingWork[buildingId]={orders:[],history:[]};const s=state.buildingWork[buildingId];if(!Array.isArray(s.orders))s.orders=[];if(!Array.isArray(s.history))s.history=[];return s;}
  function slots(buildingId){if(!C.built(buildingId))return 0;return Math.max(0,Math.floor(num(C.buildingEffect(buildingId,'jobSlots',defsFor(buildingId).length?1:0))));}
  function efficiency(buildingId){return Math.max(.2,num(C.buildingEffect(buildingId,'workEfficiency',1),1)*num(C.foodWorkModifier?.(),1));}
  function activeOrders(buildingId){return workState(buildingId).orders.filter(x=>x.status==='running'||x.status==='waiting_storage');}
  function runningOrders(){return Object.keys(state.buildingWork).flatMap(id=>workState(id).orders).filter(x=>x.status==='running');}
  function workersBusy(){return runningOrders().reduce((n,x)=>n+Math.max(1,num(x.workers,1)),0);}
  function workersTotal(){return Math.max(0,Math.floor(num(state.population,0)));}
  function workersFree(){return Math.max(0,workersTotal()-workersBusy());}
  function resourceName(id){return C.content.resources.find(r=>r.id===id)?.name||id;}
  function resourceIcon(id){return C.content.resources.find(r=>r.id===id)?.icon||'📦';}
  function hunterEcologyRule(){return (C.content.hunterEcologyRules||[])[0]||{initialPopulationFactor:.72,closureRatio:.18};}
  function hunterGround(id){return (C.content.hunterGrounds||[]).find(g=>g.id===id)||null;}
  function hunterSpecies(id){return (C.content.hunterSpecies||[]).find(sp=>sp.id===id)||null;}
  function ensureHunterEcologyPopulation(groundId,speciesId){const hs=C.jobState('hunter');if(!hs.hunt||typeof hs.hunt!=='object')hs.hunt={};if(!hs.hunt.ecology||typeof hs.hunt.ecology!=='object')hs.hunt.ecology={};const E=hs.hunt.ecology;if(!E.populations||typeof E.populations!=='object')E.populations={};if(!E.groundPressure||typeof E.groundPressure!=='object')E.groundPressure={};if(!E.populations[groundId]||typeof E.populations[groundId]!=='object')E.populations[groundId]={};const g=hunterGround(groundId),cap=Math.max(0,num(g?.populationCaps?.[speciesId],0));if(cap<=0)return null;if(!E.populations[groundId][speciesId]||typeof E.populations[groundId][speciesId]!=='object')E.populations[groundId][speciesId]={count:cap*num(hunterEcologyRule().initialPopulationFactor,.72),harvestedSeason:0,seasonKey:'',lastStatus:'',lastUpdateDay:0};if(!Number.isFinite(Number(E.groundPressure[groundId])))E.groundPressure[groundId]=0;return E.populations[groundId][speciesId];}
  function hunterEcologyReserved(groundId,speciesId,excludeOrderId=''){let total=0;for(const [buildingId] of Object.entries(state.buildingWork||{})){for(const order of workState(buildingId).orders||[]){if(order?.id===excludeOrderId||order?.ecologyApplied||!['queued','running','waiting_storage'].includes(order?.status))continue;const def=workDef(order.defId);if(def?.jobId!=='hunter'||!Array.isArray(def.ecologyImpact))continue;for(const x of def.ecologyImpact)if(x.groundId===groundId&&x.speciesId===speciesId)total+=Math.max(0,num(x.count,0));}}return total;}
  function hunterEcologyReady(def,excludeOrderId=''){if(def?.jobId!=='hunter'||!Array.isArray(def.ecologyImpact)||!def.ecologyImpact.length)return true;const rule=hunterEcologyRule();return def.ecologyImpact.every(x=>{const g=hunterGround(x.groundId),sp=hunterSpecies(x.speciesId),ps=ensureHunterEcologyPopulation(x.groundId,x.speciesId),cap=Math.max(0,num(g?.populationCaps?.[x.speciesId],0)),closure=Math.max(num(rule.closureRatio,.18),num(sp?.criticalRatio,0)),reserved=hunterEcologyReserved(x.groundId,x.speciesId,excludeOrderId);return !!ps&&num(ps.count,0)-reserved-num(x.count,0)>=cap*closure;});}
  function hunterEcologyRequirement(def,excludeOrderId=''){return hunterEcologyReady(def,excludeOrderId)?'':'Population cible réservée ou en fermeture conservatoire';}
  function applyHunterEcologyImpact(order,def){if(order?.ecologyApplied||def?.jobId!=='hunter'||!Array.isArray(def.ecologyImpact)||!def.ecologyImpact.length)return;const hs=C.jobState('hunter');hs.stats=Object.assign({autonomousEcologyHarvests:0},hs.stats||{});let removed=0;for(const x of def.ecologyImpact){const g=hunterGround(x.groundId),ps=ensureHunterEcologyPopulation(x.groundId,x.speciesId);if(!g||!ps)continue;const cap=Math.max(0,num(g.populationCaps?.[x.speciesId],0)),take=Math.min(num(x.count,0),num(ps.count,0));ps.count=Math.max(0,Math.min(cap,num(ps.count,0)-take));const E=hs.hunt.ecology;E.groundPressure[x.groundId]=Math.max(0,Math.min(100,num(E.groundPressure[x.groundId],0)+num(x.pressure,0)));ps.harvestedSeason=num(ps.harvestedSeason,0)+take;removed+=take;}hs.stats.autonomousEcologyHarvests=num(hs.stats.autonomousEcologyHarvests,0)+removed;order.ecologyApplied=true;}
  function availableInput(def,id){return def?.buildingId==='farm'&&num(C.seedReserveTarget?.(id),0)>0?num(C.seedUsable?.(id),C.resource(id)):C.resource(id);}function orderRequirements(def,excludeOrderId=''){const out=[];if(!def)return ['Ordre inconnu'];if(!C.built(def.buildingId))out.push('Bâtiment non construit');const bl=C.buildingLevel(def.buildingId);if(bl<num(def.minBuildingLevel,1))out.push(`Bâtiment niv. ${def.minBuildingLevel}`);if(def.jobId){const lvl=C.jobState(def.jobId).level;if(lvl<num(def.minJobLevel,1))out.push(`${C.job(def.jobId)?.name||def.jobId} niv. ${def.minJobLevel}`);}for(const [rid,q] of Object.entries(def.inputs||{})){const have=availableInput(def,rid);if(have<num(q))out.push(`${resourceName(rid)} ${Math.round(have*100)/100}/${q}${def.buildingId==='farm'&&num(C.seedReserveTarget?.(rid),0)>0?' utilisable(s)':''}`);}const eco=hunterEcologyRequirement(def,excludeOrderId);if(eco)out.push(eco);return out;}
  function canQueue(buildingId,defId){const def=workDef(defId);return !!def&&def.buildingId===buildingId&&orderRequirements(def).filter(x=>!x.includes('/')||x.startsWith('Bâtiment')||x.includes('niv.')).length===0;}
  function queue(buildingId,defId,count=1){const def=workDef(defId),s=workState(buildingId);if(!def||def.buildingId!==buildingId||!C.built(buildingId)||!hunterEcologyReady(def))return false;const gate=orderRequirements(def).filter(x=>x.startsWith('Bâtiment')||x.includes(' niv. '));if(gate.length)return false;let added=0;count=Math.max(1,Math.min(5,Math.floor(num(count,1))));for(let i=0;i<count;i++){if(s.orders.length>=12||!hunterEcologyReady(def))break;s.orders.push({id:uid(),defId:def.id,status:'queued',queuedAt:now(),workers:Math.max(1,Math.floor(num(def.workers,1)))});added++;}if(added){state.villageStats.autonomousJobsQueued+=added;C.log(`${def.icon||'⚙️'} ${added>1?`${added} × `:''}${def.name} ajouté${added>1?'s':''} à la file de ${C.building(buildingId)?.name||buildingId}.`);process();C.save();notify();}return added>0;}
  function cancel(buildingId,orderId){const s=workState(buildingId),i=s.orders.findIndex(x=>x.id===orderId&&x.status==='queued');if(i<0)return false;const o=s.orders[i],d=workDef(o.defId);s.orders.splice(i,1);C.log(`↩ ${d?.name||'Ordre'} retiré de la file de ${C.building(buildingId)?.name||buildingId}.`);C.save();notify();return true;}
  function inputsReady(def,excludeOrderId=''){return Object.entries(def.inputs||{}).every(([id,q])=>availableInput(def,id)>=num(q))&&hunterEcologyReady(def,excludeOrderId);}
  function consumeInputs(def,excludeOrderId=''){if(!inputsReady(def,excludeOrderId))return false;for(const [id,q] of Object.entries(def.inputs||{}))C.consumeResource(id,num(q),`Job autonome : ${def.name}`);return true;}
  function outputWeight(def){return Object.entries(def.outputs||{}).reduce((n,[id,q])=>n+num(q)*C.storageWeight(id),0);}
  function canStore(def){return C.storageFree()+1e-9>=outputWeight(def);}
  function storeOutputs(def){if(!canStore(def))return false;for(const [id,q] of Object.entries(def.outputs||{})){const accepted=C.addResource(id,num(q),`Production autonome : ${def.name}`);if(accepted<num(q))return false;}return true;}
  function grantWorkReward(order,def){if(order.rewardGranted)return;order.rewardGranted=true;if(def.jobId&&num(def.jobXp)>0)C.gainJobXp(def.jobId,num(def.jobXp));if(def.jobId&&num(def.masteryXp)>0)C.gainMastery(def.jobId,num(def.masteryXp));if(num(def.villageXp)>0)C.gainVillageXp(num(def.villageXp));}
  function finishStored(buildingId,order,def){const s=workState(buildingId);applyHunterEcologyImpact(order,def);order.status='done';order.completedAt=num(order.finishedWorkAt,now());s.resumeAt=s.resumeAt?Math.min(num(s.resumeAt),order.completedAt):order.completedAt;s.history.unshift({id:order.id,defId:order.defId,startedAt:order.startedAt,completedAt:order.completedAt});s.history=s.history.slice(0,40);s.orders=s.orders.filter(x=>x.id!==order.id);state.villageStats.autonomousJobsCompleted++;C.log(`✅ ${def.name} terminé à ${C.building(buildingId)?.name||buildingId}.`);}
  function startQueued(buildingId,startAt=now()){const s=workState(buildingId);let changed=false,started=false;startAt=Math.min(startAt,s.resumeAt?num(s.resumeAt,startAt):startAt);while(activeOrders(buildingId).length<slots(buildingId)){const o=s.orders.find(x=>x.status==='queued');if(!o)break;const d=workDef(o.defId);if(!d){s.orders=s.orders.filter(x=>x!==o);changed=true;continue;}const workers=Math.max(1,num(d.workers,1));if(workersFree()<workers)break;if(!inputsReady(d,o.id))break;if(orderRequirements(d,o.id).some(x=>x.startsWith('Bâtiment')||x.includes(' niv. ')))break;if(!consumeInputs(d,o.id))break;const duration=Math.max(1000,Math.round(num(d.duration,30)*1000/efficiency(buildingId)));o.status='running';o.workers=workers;o.startedAt=startAt;o.durationMs=duration;o.endsAt=startAt+duration;changed=true;started=true;}if(started)s.resumeAt=0;return changed;}
  function process(){let changed=false;const t=now();if(C.processFoodSecurity?.(t))changed=true;let guard=0,again=true;
    // Une boucle bornée permet à une file déjà lancée de rattraper le temps écoulé hors écran / hors session.
    while(again&&guard++<40){again=false;
      for(const b of C.content.buildings||[]){if(!C.built(b.id))continue;const s=workState(b.id);for(const o of [...s.orders]){if(o.status==='running'&&num(o.endsAt)>0&&num(o.endsAt)<=t){const d=workDef(o.defId);if(!d){s.orders=s.orders.filter(x=>x!==o);changed=again=true;continue;}grantWorkReward(o,d);o.status='waiting_storage';o.finishedWorkAt=num(o.endsAt,t);changed=again=true;}}}
      for(const b of C.content.buildings||[]){if(!C.built(b.id))continue;const s=workState(b.id);for(const o of [...s.orders]){if(o.status!=='waiting_storage')continue;const d=workDef(o.defId);if(!d){s.orders=s.orders.filter(x=>x!==o);changed=again=true;continue;}if(storeOutputs(d)){finishStored(b.id,o,d);changed=again=true;}}}
      for(const b of C.content.buildings||[]){if(!C.built(b.id))continue;const s=workState(b.id),startAt=s.resumeAt?Math.min(t,num(s.resumeAt,t)):t;if(startQueued(b.id,startAt)){changed=true;if(workState(b.id).orders.some(o=>o.status==='running'&&num(o.endsAt)<=t))again=true;}}
    }
    if(changed){C.save();notify();}return changed;
  }
  function status(buildingId){const s=workState(buildingId),active=s.orders.filter(x=>x.status==='running'),blocked=s.orders.filter(x=>x.status==='waiting_storage'),queued=s.orders.filter(x=>x.status==='queued'),next=active.sort((a,b)=>num(a.endsAt)-num(b.endsAt))[0];return {buildingId,slots:slots(buildingId),active,blocked,queued,next,orders:s.orders,history:s.history};}
  function stats(){return {workersTotal:workersTotal(),workersBusy:workersBusy(),workersFree:workersFree(),active:runningOrders().length,queued:Object.keys(state.buildingWork).reduce((n,id)=>n+workState(id).orders.filter(x=>x.status==='queued').length,0),blocked:Object.keys(state.buildingWork).reduce((n,id)=>n+workState(id).orders.filter(x=>x.status==='waiting_storage').length,0)};}
  function fmt(ms){let sec=Math.max(0,Math.ceil(num(ms)/1000));const m=Math.floor(sec/60);sec%=60;return m?`${m}:${String(sec).padStart(2,'0')}`:`${sec}s`;}
  function remaining(order){return order?.status==='running'?Math.max(0,num(order.endsAt)-now()):0;}
  function notify(){try{window.dispatchEvent(new CustomEvent('village:autonomy',{detail:stats()}));}catch{}}

  Object.assign(C,{workDef,buildingWorkDefs:defsFor,buildingWorkState:workState,buildingJobSlots:slots,queueBuildingWork:queue,cancelBuildingWork:cancel,processBuildingWork:process,buildingWorkStatus:status,autonomyStats:stats,autonomyWorkersFree:workersFree,autonomyFormatDuration:fmt,autonomyRemaining:remaining,autonomyRequirementMessages:orderRequirements});
  process();
  setInterval(process,500);
})();
