(() => {
  const C=window.VillageCore,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]||c));
  const resDef=id=>C.content.resources.find(r=>r.id===id);
  const marketPrice=id=>Number(C.lumberMarketItem(id)?.basePrice||C.miningMarketItem(id)?.basePrice||0);
  const qualityLabel=q=>q>=92?'Exceptionnelle':q>=80?'Excellente':q>=65?'Sélectionnée':q>=45?'Standard':'Ordinaire';
  function money(n){return `${Math.round(Number(n||0)*10)/10} cr.`;}
  function quickSalePrice(id){const p=marketPrice(id);return p>0?Math.max(1,Math.floor(p*.75)):0;}
  function sellWarehouseResource(id,all=false){const have=C.resource(id);if(have<=0)return;const unit=quickSalePrice(id);if(unit<=0)return alert('Aucun acheteur rapide pour cette ressource. Tu peux l’écarter pour libérer de la place.');const qty=all?have:1;if(all&&!confirm(`Vendre tout le stock de ${resDef(id)?.name||id} (${qty}) en liquidation ?`))return;if(!C.consumeResource(id,qty,'Vente rapide Entrepôt'))return;const total=unit*qty;C.state.treasury+=total;C.log(`🪙 Vente rapide depuis l’Entrepôt : ${qty} ${resDef(id)?.name||id} pour ${total} couronnes.`);C.save();render();}
  function discardWarehouseResource(id,all=false){const have=C.resource(id);if(have<=0)return;const qty=all?have:1,name=resDef(id)?.name||id;if(!confirm(all?`Écarter TOUT le stock de ${name} (${qty}) ? Cette action est irréversible.`:`Écarter 1 ${name} pour libérer du stockage ?`))return;if(!C.consumeResource(id,qty,'Mise au rebut Entrepôt'))return;C.log(`🗑️ ${qty} ${name} écarté(s) de l’Entrepôt pour libérer de la place.`);C.save();render();}
  window.warehouseSellResource=sellWarehouseResource;window.warehouseDiscardResource=discardWarehouseResource;

  function renderOverview(){const used=C.storageUsed(),cap=C.storageCapacity(),free=C.storageFree(),lvl=C.buildingLevel('warehouse'),filled=cap?used/cap:1,nonzero=C.content.resources.filter(r=>C.resource(r.id)>0).length,indicative=C.content.resources.reduce((n,r)=>n+C.resource(r.id)*marketPrice(r.id),0);$('#warehouseOverview').innerHTML=`<div class="metric"><span>Entrepôt</span><b>Niveau ${lvl}/${C.buildingMaxLevel('warehouse')}</b></div><div class="metric grow"><span>Occupation</span><b>${Math.round(used)} / ${Math.round(cap)} unités</b><div class="progress storage-progress ${filled>.9?'warn':''}"><i style="width:${Math.min(100,filled*100)}%"></i></div></div><div class="metric"><span>Place libre</span><b>${Math.round(free)}</b></div><div class="metric"><span>Ressources présentes</span><b>${nonzero}/${C.content.resources.length}</b></div><div class="metric"><span>Valeur de base indicative</span><b>${money(indicative)}</b></div>`;}
  function renderFoodSecurity(){
    const host=$('#warehouseFoodSecurity');if(!host||!C.foodSecurityStatus)return;
    const st=C.foodSecurityStatus(),active=C.built('farm'),f=C.foodState(),policy=C.foodPolicy(),target=C.foodTargetDays();
    if(!active){host.innerHTML='<div class="food-inactive"><span>🧺</span><div><b>Subsistance initiale</b><p>Avant la Ferme (accessible au niveau 2), aucune ration agricole n’est consommée et aucune pénurie ne peut se déclencher. Les habitants vivent temporairement de provisions fondatrices et de subsistance locale.</p></div></div>';return;}
    const rows=C.foodReserveComposition().filter(x=>x.quantity>.001),total=C.foodReserveUnits(),pres=Math.max(0,Math.min(1,Number(C.buildingEffect('warehouse','foodPreservation',1)))),lossReduction=Math.round((1-pres)*100),days=st.normalDays||0;
    host.innerHTML=`<div class="warehouse-food-summary ${st.id}"><div class="food-status-mark"><span>${st.icon}</span><div><small>Sécurité alimentaire</small><b>${esc(st.label)}</b><em>${Math.round(st.score||0)}/100</em></div></div><div class="food-reserve-main"><div><small>Réserve totale</small><b>${total.toFixed(1)} rations</b><span>${days.toFixed(days<10?1:0)} jours normaux · objectif ${target}</span></div></div><div class="food-kpis"><span>${policy.icon||'🍲'} <b>${esc(policy.name)}</b></span><span>🧊 Conservation <b>−${lossReduction}% pertes</b></span><span>🗑️ Pertes cumulées <b>${Number(f.stats?.foodQtySpoiled||0).toFixed(1)} u.</b></span></div></div><div class="food-stock-list">${rows.length?rows.map(x=>`<div class="food-stock-row"><span>${x.icon}</span><div><b>${esc(x.name)}</b><small>${esc(x.group)} · ${Math.round(x.spoilagePerDay*1000)/10}% de perte/jour avant bonus</small></div><strong>${x.quantity.toFixed(1)} <small>→ ${x.units.toFixed(1)} ration${x.units>=2?'s':''}</small></strong></div>`).join(''):'<div class="empty-state compact"><b>Grenier alimentaire vide</b><span>Les récoltes comestibles apparaîtront ici.</span></div>'}</div><div class="notice subtle"><b>Conservation :</b> le niveau ${C.buildingLevel('warehouse')} de l’Entrepôt applique un facteur de ${Math.round(pres*100)}% aux pertes naturelles des aliments. Les céréales se conservent mieux que les légumes frais.</div>`;
  }
  function renderUpgrade(){const b=C.building('warehouse'),lvl=C.buildingLevel('warehouse'),cur=C.buildingLevelDef('warehouse'),next=C.nextBuildingLevel('warehouse'),missing=C.missingForBuildingUpgrade('warehouse');$('#warehouseLevelBadge').textContent=`Niveau ${lvl} · ${cur?.name||''}`;if(!next){$('#warehouseUpgrade').innerHTML=`<div class="village-stage-complete"><b>🏛️ Halle des réserves achevée</b><span>Capacité actuelle : ${C.storageCapacity()} unités.</span></div>`;return;}const cost=Object.entries(next.cost||{}).map(([id,q])=>{const r=resDef(id);return `${r?.icon||'📦'} ${r?.name||id} ×${q}`}).join(' · ');$('#warehouseUpgrade').innerHTML=`<div class="warehouse-upgrade-grid"><div><small>Prochaine évolution</small><h3>Niv. ${next.level} — ${esc(next.name)}</h3><p>${esc(next.description||'')}</p><b>Capacité : ${C.storageCapacity()} → ${next.effects?.storageCapacity||'?'} unités</b></div><div><small>Coût</small><p>${esc(cost||'Aucun coût')}</p>${missing.length?`<div class="requirements compact">${missing.map(x=>`<span>• ${esc(x)}</span>`).join('')}</div>`:''}<button class="btn primary" id="upgradeWarehouseBtn" ${C.canUpgradeBuilding('warehouse')?'':'disabled'}>⬆ Améliorer l’Entrepôt</button></div></div>`;const btn=$('#upgradeWarehouseBtn');if(btn)btn.onclick=()=>{if(C.upgradeBuilding('warehouse'))render();};}
  function initFilters(){const cats=[...new Set(C.content.resources.map(r=>r.category||'autre'))].sort();$('#warehouseCategory').innerHTML='<option value="">Toutes catégories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#warehouseCategory').onchange=renderResources;$('#warehouseSearch').oninput=renderResources;}
  function renderResources(){const cat=$('#warehouseCategory').value,q=$('#warehouseSearch').value.trim().toLowerCase();const rows=C.content.resources.filter(r=>(!cat||r.category===cat)&&(!q||`${r.name} ${r.id}`.toLowerCase().includes(q)));$('#warehouseResources').innerHTML=rows.map(r=>{const qty=C.resource(r.id),produced=Number(C.state.villageStats?.resourceProduced?.[r.id]||0),value=qty*marketPrice(r.id),pct=C.storageCapacity()?qty*C.storageWeight(r.id)/C.storageCapacity()*100:0,quick=quickSalePrice(r.id);return `<article class="warehouse-resource ${qty?'has-stock':'empty'}"><div class="warehouse-resource-head"><span>${r.icon||'📦'}</span><div><b>${esc(r.name)}</b><small>${esc(r.category||'autre')}</small></div><strong>${Math.round(qty*100)/100}</strong></div><p>${esc(r.description||'')}</p><div class="warehouse-resource-meta"><span>Produit carrière <b>${Math.round(produced)}</b></span>${Number(r.starting||0)>0?`<span>Stock fondateur <b>${Number(r.starting||0)}</b></span>`:''}<span>Occupation <b>${pct.toFixed(1)}%</b></span>${r.future?`<span class="future-resource">⏳ Filière future <b>${esc(r.sourceHint||'Non encore disponible')}</b></span>`:''}${marketPrice(r.id)?`<span>Valeur base <b>${money(value)}</b></span>`:''}</div>${qty>0?`<div class="warehouse-safety-actions">${quick?`<button class="btn" onclick="warehouseSellResource('${r.id}',false)">🪙 Vendre 1 · ${quick} cr.</button><button class="btn" onclick="warehouseSellResource('${r.id}',true)">Tout vendre</button>`:''}<button class="btn danger" onclick="warehouseDiscardResource('${r.id}',false)">🗑️ Écarter 1</button><button class="btn danger subtle-danger" onclick="warehouseDiscardResource('${r.id}',true)">Tout écarter</button></div>`:''}</article>`}).join('')||'<p class="muted">Aucune ressource ne correspond aux filtres.</p>';}
  function renderBreakdown(){const groups={};for(const r of C.content.resources){const qty=C.resource(r.id)*C.storageWeight(r.id);if(qty<=0)continue;groups[r.category||'autre']=(groups[r.category||'autre']||0)+qty;}const total=C.storageUsed()||1;$('#warehouseBreakdown').innerHTML=`<div class="storage-big"><b>${Math.round(C.storageUsed())}</b><span>/ ${Math.round(C.storageCapacity())} unités</span></div>${Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="storage-break-row"><div><span>${esc(k)}</span><b>${Math.round(v)} u.</b></div><div class="mini-progress"><i style="width:${Math.min(100,v/total*100)}%"></i></div></div>`).join('')}<div class="notice subtle ${C.storageFree()<=0?'danger-note':''}">${C.storageFree()<=0?'⚠️ Entrepôt plein : aucun soft-lock. Vends, écarte, consomme ou améliore le bâtiment pour libérer de la place.':C.storageFree()<C.storageCapacity()*.12?'⚠️ L’Entrepôt approche de la saturation.':'✓ La capacité de stockage est suffisante pour le moment.'}</div>`;}
  function lotDetails(id,l){if(id==='wood')return `${qualityLabel(Number(l.quality||0))} · qualité ${Math.round(l.quality||0)}/100 · humidité ${Math.round(l.moisture||0)}%${l.treeId?` · ${C.tree(l.treeId)?.name||l.treeId}`:''}`;if(['wheat','carrot','beans','sun_spelt','ruby_beet','moon_bean'].includes(id))return `${qualityLabel(Number(l.quality||0))} · qualité ${Math.round(l.quality||0)}/100${l.cropName?` · ${l.cropName}`:''}${l.soilName?` · ${l.soilName}`:''}${l.plotNo?` · parcelle ${l.plotNo}`:''}`;return `Pureté ${Math.round(l.purity||0)}% · qualité ${Math.round(l.quality||0)}/100${l.depth!=null?` · ${Math.round(l.depth)} m`:''}${l.depositId?` · ${C.mineralDeposit(l.depositId)?.name||l.depositId}`:''}`;}
  function renderLots(){const all=[];for(const [id,lots] of Object.entries(C.state.materialLots||{}))for(const l of lots||[])all.push({id,l,type:'material'});const al=C.jobState('alchemist');for(const l of al?.alchemicalLots||[])if(Number(l.quantity||0)>0)all.push({id:l.resourceId,l,type:'alchemy'});all.sort((a,b)=>Number(b.l.createdAt||0)-Number(a.l.createdAt||0));$('#warehouseLots').innerHTML=all.length?`<div class="warehouse-lot-list">${all.map(({id,l,type})=>{const r=resDef(id),details=type==='alchemy'?`Qualité ${Math.round(l.quality||0)}/100 · stabilité ${Math.round(l.stability||0)}% · matière Q${Math.round(l.inputQuality||45)}${Number(l.traceableInput||0)>0?` · ${Math.round(Number(l.traceableInput||0)*100)/100} u. traçables`:''}`:lotDetails(id,l);return `<div class="warehouse-lot"><span>${r?.icon||'📦'}</span><div><b>${esc(r?.name||id)} ×${Math.round(Number(l.quantity||0)*100)/100}</b><small>${esc(details)}</small></div></div>`}).join('')}</div>`:'<p class="muted">Aucun lot qualitatif stocké pour le moment.</p>';}
  function renderBuildings(){const built=C.content.buildings.filter(b=>C.built(b.id));$('#warehouseBuildings').innerHTML=`<div class="warehouse-building-list">${built.map(b=>{const lvl=C.buildingLevel(b.id),max=C.buildingMaxLevel(b.id),next=C.nextBuildingLevel(b.id),w=C.buildingWorkStatus?C.buildingWorkStatus(b.id):null,activity=w&&w.active.length?` · ${w.active.length} job(s) actif(s)`:w&&w.blocked.length?' · production en attente':'';return `<div class="warehouse-building-row"><span>${b.icon||'🏠'}</span><div><b>${esc(b.name)}</b><small>Niveau ${lvl}/${max}${next?` · prochain : ${esc(next.name||`niveau ${next.level}`)}`:' · maximum'}${activity}</small></div><div class="building-level-pips">${Array.from({length:max},(_,i)=>`<i class="${i<lvl?'on':''}"></i>`).join('')}</div></div>`}).join('')}</div>`;}
  function renderLedger(){const rows=C.state.inventoryLedger||[];$('#warehouseLedger').innerHTML=rows.length?rows.map(x=>{const r=resDef(x.id),incoming=x.type==='in';return `<div class="ledger-row ${incoming?'in':'out'}"><time>${new Date(x.t).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><span>${r?.icon||'📦'} ${esc(r?.name||x.id)}</span><b>${incoming?'+':'−'}${Math.round(Number(x.qty||0)*100)/100}</b><small>${esc(x.reason||'Mouvement')}</small></div>`}).join(''):'<p class="muted">Le journal commencera à enregistrer les prochaines entrées et sorties de stock.</p>';}
  function render(){C.processFoodSecurity?.();renderOverview();renderFoodSecurity();renderUpgrade();renderResources();renderBreakdown();renderLots();renderBuildings();renderLedger();C.save();}
  $('#saveWarehouseBtn').onclick=()=>{C.save();C.log('Sauvegarde locale effectuée depuis l’Entrepôt.');renderLedger();};initFilters();render();window.addEventListener('village:autonomy',render);window.addEventListener('village:food',renderFoodSecurity);
})();
